### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by evandegr** [lalitkapoor/webpack-es6-react-boilerplate#3]
After cloning and running an npm install I attempted to do a webpack build and got the following error:

```
$ webpack
Hash: 6b1893c245de6a6f5d01
Version: webpack 1.8.11
Time: 551ms
    + 1 hidden modules

ERROR in ./public/js/app.jsx
Module build failed: Error: Parse Error: Line 1: Illegal import declaration
    at throwError (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2813:21)
    at throwErrorTolerant (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2825:24)
    at parseSourceElement (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6390:17)
    at parseProgramElement (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6446:16)
    at parseProgramElements (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6478:29)
    at parseProgram (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6491:16)
    at Object.parse (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7653:23)
    at getAstForSource (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:251:21)
    at transform (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/node_modules/jstransform/src/jstransform.js:274:11)
    at innerTransform (/Users/evanvandegriff1/Work/webpack-es6-react-boilerplate/node_modules/jsx-loader/node_modules/react-tools/main.js:94:10)
```

**Comment by lalitkapoor** [comment]
@evandegr updated with latest react, webpack, babel, etc, give it a whirl

**Comment by evandegr** [comment]
Thanks that fixed it.

**Comment by weichao-ts** [comment]
can you tell more detail？ how to fixed this
